const GET_REQUEST = 'GET_REQUEST';

const GET_SUCCESS = 'GET_SUCCESS';

const GET_FAIL = 'GET_FAIL';

const REMOVE_FROH_CART = 'REMOVE_FROM_CART';

const ADD_T0_CART = 'ADD_TO_CART' ;

const USER_SIGNIN = 'USER_SIGNIN';

const USER_SIGNOUT = 'USER_SIGNOUT'

export { GET_SUCCESS, GET_FAIL, GET_REQUEST, ADD_T0_CART, REMOVE_FROH_CART, USER_SIGNIN, USER_SIGNOUT };