const data = {
  products: [
    {
      name: 'Product A Name',
      category: 'Category A',
      description: 'Product A Description',
      price: 12.99,
      token: 'Product A Token',
      brend: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 100,
      image: '/images/producta.jpg',
    },
    {
      name: 'Product B Name',
      category: 'Category B',
      description: 'Product B Description',
      price: 9.99,
      token: 'Product B Token',
      brend: 'Teva',
      countInStock: 3,
      rating: 4,
      numReviews: 200,
      image: '/images/productb.jpg',
    },
    {
      name: 'Product C Name',
      category: 'Category C',
      description: 'Product C Description',
      price: 15.99,
      token: 'Product C Token',
      brend: 'Teva',
      countInStock: 8,
      rating: 2,
      numReviews: 80,
      image: '/images/productc.jpg',
    },
    {
      name: 'Product D Name',
      category: 'Category D',
      description: 'Product D Description',
      price: 5.99,
      token: 'Product D Token',
      brend: 'Teva',
      countInStock: 9,
      rating: 3,
      numReviews: 150,
      image: '/images/productd.jpg',
    },
  ],
};

export default data;
